name: lumina_medical_center
description: "Lumina Medical Center Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.0.5
  injectable: ^2.6.0
  dio: ^5.9.0
  go_router: ^17.0.0
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.2
  json_annotation: ^4.9.0
  flutter_screenutil: ^5.9.3
  sizer: ^3.1.3
  http: ^1.6.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_floating_bottom_bar: ^1.3.0
  image_picker: ^1.2.1
  jwt_decoder: ^2.0.1
  foundation: ^0.0.5
  flutter_staggered_animations: ^1.1.1
  cached_network_image: ^3.4.1
  flutter_localization: ^0.3.3
  mask_text_input_formatter: ^2.9.0
  timeline_tile: ^2.0.0
  easy_date_timeline: ^2.0.9
  table_calendar: ^3.2.0
  fl_chart: ^1.1.1
  flutter_admin_scaffold: ^1.4.0
  data_table_2: ^2.7.2
  toastification: ^3.0.3
  responsive_framework: ^1.5.1
  sidebarx: ^0.17.2
  hugeicons: ^1.1.2
  dartz: ^0.10.1
  mockito: ^5.6.1
  build_runner: ^2.10.4
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  injectable_generator: ^2.9.1
  bloc_test: ^10.0.0
  mocktail: ^1.0.4


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/jpg/
    - assets/icons/medical/